### ISSUE TITLE
Repl not available

### ISSUE THREAD

**Issue by erawretsila** [CytronTechnologies/MAKER-PI-RP2040#1]
Hi
cant access the python repl from mu when selecting serial, get an error message saying the device cannot be detected when using the 7.0 alpha build as supplied
Works with the Cricuitputhon 6.3.0 release

**Comment by waiweng83** [comment]
Did you see the "CIRCUITPY" device in your file explorer when using the 7.0 alpha build?

**Comment by erawretsila** [comment]
yes I can see the device. editing & running code is possible I just cannot open the serial console for the python REPL which makes debuging dificult.

this is using Mu on a Raspberry Pi400 but I have also tried my dell laptop with fedora 34 & even windoze 7 out of desparation :-)
circuit python V6.3.0 is working without a hitch

**Comment by waiweng83** [comment]
Since V6.3.0 is working, it can safely rule out the hardware issue. Honestly I don't have any idea what could have gone wrong.
Did you try the absolute latest firmware? How about using Thonny instead of MU?

**Comment by erawretsila** [comment]
As far as I know it is the latest firmware
did not realise that thonny was also an option - will give that a go

**Comment by erawretsila** [comment]
OK, Just tried with thonny & all seems ok
Must be an issue with the current versions of Mu

**Comment by waiweng83** [comment]
It's great to hear that.
I'll close this for now.

Thanks.
