### ISSUE TITLE
Three calls vs One call

### ISSUE THREAD

**Issue by dmccreary** [CytronTechnologies/MAKER-PI-RP2040#2]
Thank you for your wonderful code.

One small suggestion, in the main loop:

while True:
    distance = CheckDistance()
    print(distance)
    if CheckDistance() < 10:
        Buzzer.duty_u16(3000)
        Buzzer.freq(1700)
        utime.sleep(0.05)
        Buzzer.duty_u16(0)
        utime.sleep(CheckDistance() / 1000)

You call CheckDistance() 3 times.  It might be more efficient to call it once and reference the distance variable:

while True:
    distance = CheckDistance()
    print(distance)
    if distance < 10:
        Buzzer.duty_u16(3000)
        Buzzer.freq(1700)
        utime.sleep(0.05)
        Buzzer.duty_u16(0)
        utime.sleep(distance/ 1000)

**Comment by kiate** [comment]
Hi, thanks for the feedback. But may I know which code are you referring to?
